# Configuration for both train.py and evaluate.py

autoregressive_imputation: true

# Data & paths
folder_to_load: "2024-03-01_35"
geojson_path: "sensors_location.geojson"
save_folder: "weights"
output_csv: "evaluation_results.csv"

# Train/val/test split (fractions)
train_size: 0.5
val_size: 0.2

# Graph parameters
sigma2: 0.1
epsilon: 0.95

# Delaunay settings
use_delaunay: true
max_depth: 5
adj_scaler_options:
  - 0
  - 1
  - 2

# Model / data parameters
in_feat: 1
out_feat: 10
lstm_units: 64
graph_conv_params:
  aggregation_type: "mean"
  combination_type: "concat"
  activation: null

# Training loop settings
epochs: 40
batch_size: 64
input_seq_len: 12
forecast_horizons:
  - 1
  - 2
  - 3
seeds: [0,1,2,3,4,5,6,7,8,9]

# temp, for testing purpose
original_csv: "combined_sensors_2023-01-01_2023-01-31.csv"
masked_csv: "data_masked.csv"
metrics_json: "metrics.json"
filled_csv: "imputed_values.csv"

#new stuff

# single wide CSV
data_csv: "combined_sensors_2023-01-01_2023-01-31.csv"

# output wide filled (after imputation)
output_csv: "data_filled.csv"

# data_imputation masking
apply_masking: true
impute_num_records: 144
impute_num_columns: "all"
impute_columns: null   # or specific columns ["A001", "A010"]
masked_values_csv: "masked_values.csv"

summary_csv: "imputation_summary.csv"
gui_results_csv: "gui_results.csv"

ar_batch_size: 64

baseline_method: "rolling_mean"    # albo: ffill_bfill, median, rolling_mean, spline, knn_columns
# albo grafowe:
# baseline_method: "graph_laplacian", "graph_temporal"
edges_csv: "edges.csv"       # wymagane tylko dla graph_*
lam: 1.0
lam_time: 0.1